version: '3.5'

services:
  redis:
    container_name: "redis"
    image: redis:alpine
    command: --save 900 1
    volumes:
      - /data/redis:/data
    restart: on-failure:5
    ports:
      - "6379:6379"
    network_mode: "host"
  ntopng:
    container_name: "ntopng"
    build:
      dockerfile: ./ntopng/Dockerfile
    command: ntopng --community -i wlan0 -w localhost:3000 -r localhost:6379 -d /ntopngcustom
    volumes:
      - /data/ntopng:/ntopng
    restart: on-failure:5
    network_mode: "host"
    depends_on:
      - redis
  backend:
    container_name: "backend"
    build:
      context: backend
      dockerfile: ./Dockerfile
    network_mode: "host"
